#! /bin/sh

##
# Credit
# https://github.com/leosartaj/credit.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

# installed directory
INSTALL_DIR='/usr/local/credit'

help_credit()
{
  echo "Usage: $0"
  echo "  -h : Displays this help"
  echo "  [display] : Displays all the account names"
  echo "  [net] : Displays the net total considering all accounts"
  echo "  [new] [account_name] : Adds a new account"
  echo "  [delete] [account_name] : Deletes the account"
  echo "  [print] [account_name] : Print the contents of the account"
  echo "  [total] [account_name] : Gives the net balance"
  echo "  [totals] : Gives the net balance of each account"
  echo "  [reset] [account_name] : Reset the account contents to 0"
  echo "  [update] [account_name] [+/-Num] : Add an entry"
  exit 1
}

# default value for $CREDIT_DIR
if [ -z "$CREDIT_DIR" ]; then
  CREDIT_DIR=~/.credit
fi

if [ ! -d $CREDIT_DIR ]
then
    mkdir $CREDIT_DIR           # Make directory if directory does not exist
fi

# If no command-line args, display help and exit
if [ $# -lt 1 ]; then
  help_credit
fi

# If more than one command line argument, display help and exit
if [ $# -gt 3 ]; then
  help_credit
fi

# Parse arguments
while getopts h opt
do
  case "$opt" in
      h) help_credit;;
      \?) help_credit;;
  esac
done

if [ $# -eq 1 ]; then
  if [ "$1" = "display" ]; then
    python2.7 "$INSTALL_DIR/display.py" "$CREDIT_DIR" 
  elif [ "$1" = "net" ]; then
    python2.7 "$INSTALL_DIR/net.py" "$CREDIT_DIR" 
  elif [ "$1" = "totals" ]; then
    python2.7 "$INSTALL_DIR/total_all.py" "$CREDIT_DIR" 
  else
    help_credit
  fi
fi

if [ $# -eq 2 ]; then
  if [ "$1" = "new" ]; then
    python2.7 "$INSTALL_DIR/new.py" "$2" "$CREDIT_DIR" 
  elif [ "$1" = "delete" ]; then
    python2.7 "$INSTALL_DIR/delete.py" "$2" "$CREDIT_DIR" 
  elif [ "$1" = "print" ]; then
    python2.7 "$INSTALL_DIR/display_acc.py" "$2" "$CREDIT_DIR" 
  elif [ "$1" = "reset" ]; then
    python2.7 "$INSTALL_DIR/reset.py" "$2" "$CREDIT_DIR" 
  elif [ "$1" = "total" ]; then
    python2.7 "$INSTALL_DIR/total.py" "$2" "$CREDIT_DIR" 
  else
    help_credit
  fi
fi

if [ $# -eq 3 ]; then
  if [ "$1" = "update" ]; then
    python2.7 "$INSTALL_DIR/update.py" "$2" "$3" "$CREDIT_DIR" 
  else
    help_credit
  fi
fi
