#! /usr/bin/sh

##
# Credit
# https://github.com/MnC-69/credit.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

# installed directory
INSTALL_DIR='/usr/local/credit'

help_credit()
{
  echo "Usage: $0 <flag>"
  echo "Valid flags:"
  echo "  -h : Displays this help"
  exit 1
}

# default value for $CREDIT_DIR
if [ -z "$CREDIT_DIR" ]; then
  CREDIT_DIR=~/.credit
fi

if [ ! -d $CREDIT_DIR ]
then
    mkdir $CREDIT_DIR           # Make directory if directory does not exist
fi

# If no command-line args, display help and exit
if [ $# -lt 1 ]; then
  help_credit
fi

# If more than one command line argument, display help and exit
if [ $# -gt 3 ]; then
  help_credit
fi

# Parse arguments
while getopts h opt
do
  case "$opt" in
      h) help_credit;;
      \?) help_credit;;
  esac
done

if [ "$1" = "new" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/new.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "delete" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/delete.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "display" ]; then
  if [ ! $# -eq 1 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/display.py" "$CREDIT_DIR" 
elif [ "$1" = "disacc" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/display_acc.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "rlast" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/rem_last.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "reset" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/reset.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "total" ]; then
  if [ ! $# -eq 2 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/total.py" "$2" "$CREDIT_DIR" 
elif [ "$1" = "update" ]; then
  if [ ! $# -eq 3 ]; then
    help_credit
  fi
  python2.7 "$INSTALL_DIR/update.py" "$2" "$3" "$CREDIT_DIR" 
else
  help_credit
fi
