#! /usr/bin/sh

##
# Credit
# https://github.com/MnC-69/credit.git
#
# Copyright (c) 2014 Sartaj Singh
# Licensed under the MIT license.
##

help_credit()
{
    echo "Usage: $0 <flag>"
    echo "Valid flags:"
    echo "  -h : Displays this help"
    exit 1
}

# default value for $CREDIT_DIR
if [ -z "$CREDIT_DIR" ]; then
    CREDIT_DIR=/usr/local/credit
fi

# If no command-line args, display help and exit
if [ $# -lt 1 ]; then
    help_credit
fi

# If more than one command line argument, display help and exit
if [ $# -gt 2 ]; then
    help_credit
fi

# Parse arguments
while getopts h opt
do
    case "$opt" in
        h) help_credit;;
        \?) help_credit;;
    esac
done

#if [ ! -z "$NEW_REQUEST" ]; then
    #python2.7 "$FORQ_DIR/generate.py" "$FORQ_DIR"
#fi
